# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0002_auto_20180227_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='city',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='rank',
        ),
    ]
