# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-28 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0003_auto_20180228_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
    ]
