# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0004_remove_doctor_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_doctor',
            name='doc_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pat_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SSH.patient'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Available', 'Available')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='image_doctor',
        ),
    ]
