# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0005_auto_20180306_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=20, null=True),
        ),
    ]
