# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0006_auto_20180307_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pat_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(blank=True, choices=[('Unavailable', 'Unavailable'), ('Available', 'Available')], max_length=20, null=True),
        ),
    ]
