# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0007_auto_20180308_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='app_date',
            new_name='appdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_message',
            new_name='appmessage',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='app_time',
            new_name='apptime',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_name',
            new_name='docname',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='pat_name',
            new_name='patname',
        ),
    ]
