# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0008_auto_20180308_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='docfirst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doclast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patfirst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patlast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
