# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0009_auto_20180308_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apptime',
            field=models.CharField(blank=True, choices=[('10:00 - 10:30', '10:00 - 10:30'), ('9:00 - 9:30', '9:00 - 9:30'), ('9:30 - 10:00', '9:30 - 10:00')], max_length=40, null=True),
        ),
    ]
