# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-11 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSH', '0010_auto_20180326_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='apptime',
            field=models.CharField(blank=True, choices=[('10:30 - 11:00', '10:30 - 11:00'), ('10:00 - 10:30', '10:00 - 10:30'), ('9:30 - 10:00', '9:30 - 10:00'), ('12:00 - 12:30', '12:00 - 12:30'), ('12:30 - 1:00', '12:30 - 1:00'), ('1:00 - 1:30', '1:00 - 1:30'), ('9:00 - 9:30', '9:00 - 9:30'), ('11:30 - 12:00', '11:30 - 12:00'), ('1:30 - 2:00', '1:30 - 2:00'), ('11:00 - 11:30', '11:00 - 11:30')], max_length=40, null=True),
        ),
    ]
